GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "User", "name": "User", "password": "123456"
}

###

POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "Sal", "name": "Sal Vulcano", "password": "123456"
}

###
POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "User", "password": "123456"
}

###
GET http://localhost:3001/watchlists/3

###
GET http://localhost:3001/api/instruments/

###
POST http://localhost:3001/api/watchlists/
content-type: application/json

{
    "name": "newWatchlist", "isMF": true, "user": "61f0f9ee4e819f6d7d088344"
}


